Repository 2024-Winter-BootCamp-TeamF/Backend, pull requests merged in 2025-01, with the labels that each got.

#17 [Setting/#16] OpenAI 연동 완료
  config/urls.py
  poetry.lock
  pyproject.toml
  temp/openaiService.py
  temp/urls.py
  temp/views.py
Labels: 환경 설정

#24 [feat/#19] pdf 변환
  Dockerfile
  poetry.lock
  pyproject.toml
  temp/migrations/0002_delete_uploadedpdf.py
  temp/migrations/0003_initial.py
  temp/pdf/views.py
Labels: 기능 구현

#28 [feat/#25] User
  config/settings.py
  config/urls.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/__init__.py
  user/models.py
  user/serializers.py
  user/tests.py
  user/urls.py
  user/views.py
Labels: 기능 구현

#38 [feat/#35] 페이지별 summary
  poetry.lock
  pyproject.toml
  temp/migrations/0002_pineconesummary.py
  temp/openaiService.py
  temp/pinecone/models.py
  temp/pinecone/service.py
  temp/pinecone/urls.py
  temp/pinecone/views.py
Labels: 기능 구현

#45 [feat/#42] summary 텍스트 pdf 저장
  Dockerfile
  config/settings.py
  docker-compose.yml
  poetry.lock
  pyproject.toml
  temp/pdf/urls.py
  temp/pdf/utils.py
  temp/pdf/views.py
Labels: 기능 구현

#49 [feat/#47] 프로메테우스 + 그라파나
  Dockerfile
  config/settings.py
  config/urls.py
  docker-compose.yml
  poetry.lock
  prometheus.yml
  pyproject.toml
Labels: 기능 구현

#51 [feat/#50] CORS 에러 설정
  config/settings.py
  docker-compose.yml
  poetry.lock
  pyproject.toml
Labels: 오류 수정

#53 [Setting/#52] cAdvisor, 슬랙 연동
  alert-rules.yml
  alertmanager.yml
  docker-compose.yml
  prometheus.yml
Labels: 환경 설정

#62 [Refactor/#59] pinecone 저장 비동기 처리
  config/urls.py
  docker-compose.yml
  temp/langchain/services.py
  temp/pdf/urls.py
  temp/text/__init__.py
  temp/text/services.py
  temp/text/tasks.py
  temp/text/urls.py
  temp/text/views.py
Labels: 리팩토링

#65 [Bug/#64] 파일 이름 저장 수정
  temp/pdf/utils.py
  temp/pdf/views.py
  temp/text/tasks.py
Labels: 오류 수정

#72 [bug] 토큰 자동 불러오기
  config/settings.py
  swagger/file_upload_docs.py
  temp/migrations/0004_uploadedpdf_user.py
  temp/pdf/models.py
  temp/pdf/urls.py
  temp/pdf/views.py
  user/models.py
  user/views.py
Labels: 오류 수정

#75 [Refactor/#66] 프롬프트 수정, 인코딩 변경
  config/settings.py
  docker-compose.yml
  temp/openaiService.py
Labels: 리팩토링

#89 [Refactor/#86] 개선
  config/settings.py
  temp/migrations/0001_initial.py
  temp/migrations/0002_pineconesummary.py
  temp/migrations/0003_uploadedpdf_user_morequestion_question_useranswer.py
  temp/migrations/0004_moreuseranswer.py
  temp/migrations/0005_summarypdf.py
  temp/pdf/urls.py
  temp/pinecone/urls.py
  temp/urls.py
Labels: 리팩토링

#100 [Refactor/#92] 문제 생성 오류 수정
  temp/morequestion/views.py
  temp/openaiService.py
  temp/question/views.py
Labels: 리팩토링, 오류 수정

#105 [Bug/#101] 추가연습문제 오류 수정
  temp/langchain/views.py
  temp/morequestion/views.py
  temp/pinecone/views.py
  temp/question/views.py
  temp/text/views.py
  temp/views.py
Labels: 오류 수정

#113 [Refactor/#112] top_k 고정
  temp/langchain/services.py
  temp/langchain/tasks.py
  temp/langchain/utils.py
  temp/langchain/views.py
Labels: 리팩토링
